version: '3'
services:
  app:
    container_name: top_g
    build: .
    volumes:
      - /opt/discbot/.env:/app/.env
      - /opt/discbot/assets:/assets
    env_file:
      - /opt/discbot/.env
  redis:
    container_name: redis
    ports: 
      - 6379:6379
    image: redis
